In [98]:
!pip install psycopg2
import psycopg2

Requirement already satisfied: psycopg2 in /usr/local/lib/python3.12/dist-packages (2.9.12)

In [99]:
import pandas as pd

In [100]:
import psycopg2

try:
    conn = psycopg2.connect(
        host="", # enter endpoint here
        database="ipl",
        user="postgres",
        password="hello123",
        port="5432"
    )
    conn.autocommit = True
    cur = conn.cursor()
    print("Connection established")

except Exception as e:
    print("Connection Error")
    print(type(e))
    print(e)

Connection established

In [101]:
delivery = pd.read_sql_query("SELECT * FROM deliveries;", conn)
player = pd.read_sql_query("SELECT * FROM player;", conn)
player_captain = pd.read_sql_query("SELECT * FROM player_captain;", conn)

/tmp/ipykernel_3169/3093175957.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  delivery = pd.read_sql_query("SELECT * FROM deliveries;", conn)
/tmp/ipykernel_3169/3093175957.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  player = pd.read_sql_query("SELECT * FROM player;", conn)
/tmp/ipykernel_3169/3093175957.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  player_captain = pd.read_sql_query("SELECT * FROM player_captain;", conn)

In [102]:
delivery

,match_id,inning,batting_team,bowling_team,over_num,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NA,NA,NA
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,NA,NA,NA
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NA,NA,NA
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,NA,NA,NA
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,NA,NA,NA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,None,0,NA,NA,NA
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,None,0,NA,NA,NA
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,None,0,NA,NA,NA
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,None,0,NA,NA,NA
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,None,0,NA,NA,NA

In [103]:
temp_df = player.merge(player_captain,on='player_id')[['player_name','match_id','is_captain']]
temp_df

      player_name  match_id  is_captain
0      SC Ganguly    335987           1
1      SC Ganguly    335991           1
2      SC Ganguly    335998           1
3      SC Ganguly    336002           1
4      SC Ganguly    336005           1
...           ...       ...         ...
12689   DL Chahar    981010           0
12690  P Dharmani    335988           0
12691    RV Pawar    336026           0
12692  KH Devdhar    501269           0
12693    T Mishra    548331           0

[12694 rows x 3 columns]

In [104]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over_num,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NA,NA,NA
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,NA,NA,NA
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NA,NA,NA
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,NA,NA,NA
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,None,0,NA,NA,NA

In [105]:
delivery = delivery.merge(temp_df,left_on=['match_id','batter'],right_on=['match_id','player_name'],how='left').fillna(0)
delivery

,match_id,inning,batting_team,bowling_team,over_num,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,player_name,is_captain
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NA,NA,NA,0,0.0
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,0,0,NA,NA,NA,0,0.0
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NA,NA,NA,0,0.0
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,0,0,NA,NA,NA,0,0.0
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,0,0,NA,NA,NA,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,0,0,NA,NA,NA,0,0.0
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,0,0,NA,NA,NA,0,0.0
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0,0,NA,NA,NA,0,0.0
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,0,0,NA,NA,NA,0,0.0
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,0,0,NA,NA,NA,0,0.0

In [106]:
runs = delivery.groupby(['match_id','batter'])['batsman_runs'].sum().reset_index()
balls = delivery.groupby(['match_id','batter'])['batsman_runs'].count().reset_index()
sixes = delivery.query('batsman_runs == 6').groupby(['match_id','batter'])['batsman_runs'].count().reset_index()
fours = delivery.query('batsman_runs == 4').groupby(['match_id','batter'])['batsman_runs'].count().reset_index()

In [107]:
final_df = runs.merge(balls,on=['match_id','batter'],suffixes=['_runs','_balls']).merge(fours,on=['match_id','batter'], how='left').merge(sixes,on=['match_id','batter'],how='left')
final_df.fillna(0,inplace=True)
final_df.rename(columns={
    'batsman_runs_runs': 'runs',
    'batsman_runs_balls': 'balls',
    'batsman_runs_x': 'fours',
    'batsman_runs_y': 'sixes'
}, inplace= True)
final_df

       match_id         batter  runs  balls  fours  sixes
0        335982      AA Noffke     9     12    1.0    0.0
1        335982        B Akhil     0      2    0.0    0.0
2        335982    BB McCullum   158     77   10.0   13.0
3        335982       CL White     6     10    0.0    0.0
4        335982      DJ Hussey    12     12    1.0    0.0
...         ...            ...   ...    ...    ...    ...
16510   1426312      SP Narine     6      2    0.0    1.0
16511   1426312        SS Iyer     6      3    1.0    0.0
16512   1426312  Shahbaz Ahmed     8      7    0.0    1.0
16513   1426312        TM Head     0      1    0.0    0.0
16514   1426312        VR Iyer    52     27    4.0    3.0

[16515 rows x 6 columns]

In [108]:
final_df['strike_rate'] = round((final_df['runs']/final_df['balls'])*100,2)

In [109]:
final_df = final_df.merge(temp_df, left_on=['match_id','batter'],right_on=['match_id','player_name'],how='left').drop(columns=['player_name']).fillna(0)
final_df

,match_id,batter,runs,balls,fours,sixes,strike_rate,is_captain
0,335982,AA Noffke,9,12,1.0,0.0,75.00,0.0
1,335982,B Akhil,0,2,0.0,0.0,0.00,0.0
2,335982,BB McCullum,158,77,10.0,13.0,205.19,0.0
3,335982,CL White,6,10,0.0,0.0,60.00,0.0
4,335982,DJ Hussey,12,12,1.0,0.0,100.00,0.0
...,...,...,...,...,...,...,...,...
16510,1426312,SP Narine,6,2,0.0,1.0,300.00,0.0
16511,1426312,SS Iyer,6,3,1.0,0.0,200.00,0.0
16512,1426312,Shahbaz Ahmed,8,7,0.0,1.0,114.29,0.0
16513,1426312,TM Head,0,1,0.0,0.0,0.00,0.0
16514,1426312,VR Iyer,52,27,4.0,3.0,192.59,0.0

In [110]:
def score_board(row):
  score = 0
  score = score + row['runs'] + row['fours'] + 2*row['sixes']
  if row['runs']>=100:
    score = score + 16
  elif row['runs'] >= 50:
    score = score + 8
  elif row['runs']>=30:
    score = score + 4
  elif row['runs'] == 0:
    score = score -2

  if row['balls'] >= 10:
    if row['strike_rate'] > 170:
      score = score + 6
    elif row['strike_rate'] > 150:
      score = score +4
    elif row['strike_rate'] > 130:
      score = score +2
    elif row['strike_rate'] > 60 and row['strike_rate']<=70:
      score = score -2
    elif row['strike_rate'] > 50 and row['strike_rate']<= 60:
      score = score -4
    elif row['strike_rate'] <=50:
      score = score -6

    if row["is_captain"] == 1:
      score = score*2

  return score

In [122]:
final_df['score'] = final_df.apply(score_board, axis=1)
export_df = final_df.sort_values(by='score', ascending=False)

In [121]:

cur.execute("""
CREATE SCHEMA IF NOT EXISTS analytics;
""")

conn.commit()

In [124]:
from sqlalchemy import create_engine

engine = create_engine(
    "" # enter endpoint here
)

export_df.to_sql(
    name="player_match_scores",
    con=engine,
    schema="analytics",      # <-- This is the analytics schema
    if_exists="replace",     # Use "append" if you don't want to overwrite
    index=False
)

515

In [129]:
cur.execute("""
SELECT *
FROM analytics.player_match_scores
LIMIT 10;
""")
c = cur.fetchall()
for i in c:
  print(i)

(501243, 'V Sehwag', 119, 58, 13.0, 6.0, 205.17, 1.0, 332.0)
(501210, 'SR Tendulkar', 100, 71, 12.0, 3.0, 140.85, 1.0, 272.0)
(598027, 'CH Gayle', 175, 69, 13.0, 17.0, 253.62, 0.0, 244.0)
(335982, 'BB McCullum', 158, 77, 10.0, 13.0, 205.19, 0.0, 216.0)
(548342, 'V Sehwag', 73, 43, 8.0, 4.0, 169.77, 1.0, 202.0)
(419158, 'SC Ganguly', 75, 54, 11.0, 2.0, 138.89, 1.0, 200.0)
(501266, 'MS Dhoni', 70, 40, 3.0, 6.0, 175.0, 1.0, 198.0)
(1304112, 'Q de Kock', 140, 71, 10.0, 10.0, 197.18, 0.0, 192.0)
(548372, 'V Kohli', 73, 55, 9.0, 1.0, 132.73, 1.0, 188.0)
(980987, 'AB de Villiers', 129, 53, 10.0, 12.0, 243.4, 0.0, 185.0)